services:
  syzkaller:
    image: gcr.io/syzkaller/env
    container_name: syzkaller
    stdin_open: true 
    tty: true
    privileged: true
    working_dir: /syzkaller/gopath/src/github.com/google/syzkaller
    entrypoint: /usr/bin/bash
    environment:
      - HOME=/syzkaller
      - GOPATH=/syzkaller/gopath:/gopath
      - SOURCEDIR=/syzkaller/kernel
    volumes:
      - /home/dwappner/Desktop/linux:/syzkaller/kernel:z
      - /home/dwappner/Desktop/syzkaller:/syzkaller/gopath/src/github.com/google/syzkaller:z
    restart: "no"
